### Root
GET http://{{host}}:{{port}}/

### Well Known
# @no-redirect
GET http://{{host}}:{{port}}/.well-known/jmap

### Session Test 1
GET http://{{host}}:{{port}}/jmap/session
Authorization: Bearer test1token

### Session Test 2
GET http://{{host}}:{{port}}/jmap/session
Authorization: Bearer test2token
