### Root
GET http://{{host}}:{{port}}/

### Well Known
# @no-redirect
GET http://{{host}}:{{port}}/.well-known/jmap

### Session Test 1A
GET http://{{host}}:{{port}}/jmap/session
Authorization: Bearer test123

### Session Test 1B
GET http://{{host}}:{{port}}/jmap/session
Authorization: Bearer test222

### Session Test 2
GET http://{{host}}:{{port}}/jmap/session
Authorization: Bearer test321
